<?php
// Plugin definition
$plugin = array(
  'title' => t('Creating page'),
  'icon' => 'creating-page.png',
  'category' => t('Creating'),
  'theme' => 'creating_page',
  'regions' => array(
    'featured' => t('Featured Header'),
    'sidebar' => t('Sidebar'),
    'contentheader' => t('Content Header'),
    'contentcolumn1' => t('Content Column 1'),
    'contentcolumn2' => t('Content Column 2'),
    'contentfooter' => t('Content Footer'),
  ),
);
